language: python
python:
  - "3.8"

install:
  - pip install pipenv
  - pipenv sync

script: "python -m unittest -v"

notifications:
  email:
    recipient:
      - secure: K7WwztCpVDlfV10EeT2UmS3d10+bhza2n6uHq10KJscVJ4ZjY+RF7NVTQtqvqs1ZCm3wJkLbVwAy15SfsNuHEUUhDn3JPSBHOaoBrcU26/6f/mYVokDLkFREt9N3Qkpb54fc5Igl2TwCqOGUIxvfXEYAQxNwedDPwplVqGh4O/4PNEBl/eAP+vhXrivMO3qsZovhja7NkWvv4Ftmvw59qwpmRJV7NEy+DZKpjOvyEVl4vnGi4E817eXs7XMnkzxP3tEOFDfY8AJniivapuSa/MZsxLGDCtPkEe/t5/YpzpqisWwhSl4JYsOlH5EjKliSGVcV4P9OeSVjJcSmrk4MlFhciF9+PvLYWMXvvpg53pP/Las7tXRLOsXlq7KORUNu14Si3Tw7NKUvGZQvLNB/N91z4yF4GeNBzIe3QEWdzsORQIQNEf8iaFxkYnbA6TR5x79XsBboEYvBgO3gy0pz0DOsvVz197e7PlOYZGdQec7T4YUd2JehWcuS9fV1OZ1ySS4DSG7QAKL8oP2OEee0dbQ8RYwsooE7HheRjPK9NgqYyOoWPorQmCUWOavVv2v8RzE1YVmKiWmNrLWaSISXJ7zoCCLqt71i7l0xT0x//KY7dGscS4PktiL5YZ6BYzK8mavXBjfJ2E4PuoY5vzkF4+1/7iIsvQpWQeF3NYvFY58=

    on_success: never
